### ISSUE TITLE
getting error

### ISSUE THREAD

**Issue by tvardy** [jakubgarfield/expenses#8] opened 2017-07-22 22:02 UTC
```
cb=gapi.loaded_0:82 Uncaught Object
{
  error: "idpiframe_initialization_failed",
  details: "Failed to read the 'localStorage' property from 'Window': Access is denied for this document."
}
(anonymous) @ cb=gapi.loaded_0:82
```

what can be wrong?

**Comment by jakubgarfield** [comment] 2017-07-24 06:13
Fixed and duplicate of #6

**Closed by jakubgarfield** 2017-07-24 06:13 UTC
