### ISSUE TITLE
Client Id Issue

### ISSUE THREAD

**Issue by vishnuprabhu-g** [jakubgarfield/expenses#4] opened 2017-06-22 18:21 UTC
Client id only works on localhost:8080

It won't work in localhost default static port 5000 or any other domain. Please provide steps to create new client id. I guess I need to submit for verification to access sheets api

**Comment by jakubgarfield** [comment] 2017-06-22 21:00
Duplicate of #2

**Closed by jakubgarfield** 2017-06-22 21:00 UTC
